import { Anton, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Weight } from "lucide-react";

const geistAnton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ['400']
});

const geistPlayfairDisplay = Playfair_Display({
  variable: "--font-playfairDisplay",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistAnton.variable} ${geistPlayfairDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
