import { Anton, Playfair_Display } from "next/font/google";
import "./globals.css";
import { ActiveSectionProvider } from "@/components/ActiveSectionContext";

const geistAnton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ['400']
});

const geistPlayfairDisplay = Playfair_Display({
  variable: "--font-playfairDisplay",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Junior Boni</title>
      </head>
      <body className={`${geistAnton.variable} ${geistPlayfairDisplay.variable} antialiased`}>
        <ActiveSectionProvider>
          {children}
        </ActiveSectionProvider>
      </body>
    </html>
  );
}
